[project]
name = "proyecto-isabelle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Miguel González Duque", email = "miguelgondu@gmail.com" },
    { name = "Thomas Jaramillo Aguirre", email = "tjaramilloa@unal.edu.co" },
    {name = "Jacobo Valencia lópez", email = "jacoval31@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.40.0",
    "click>=8.3.1",
    "duckdb>=1.4.4",
    "httpx>=0.28.1",
    "openai>=1.50.0",
    "pandas>=3.0.1",
    "pydantic>=2.10.0",
    "pydantic-settings>=2.0",
    "pypdf>=6.0.0",
    "rich>=14.3.3",
    "typer>=0.24.1",
]

[tool.uv]
exclude-newer = "2026-03-01"

[project.scripts]
proyecto-isabelle = "proyecto_isabelle:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ipython>=9.0.0",
]
